import { Composition } from "remotion";
import { AutoDemoVideo } from "./AutoDemoVideo";
import {
  AUTODEMO_COMPOSITION_ID,
  DEFAULT_VIDEO_CONFIG,
  type AutoDemoVideoProps,
} from "./types";
import { totalDurationInFrames } from "@/lib/video/timeline";

/**
 * Remotion Root — registers the AutoDemo composition.
 *
 * The real timeline is supplied at render time via input props. Composition
 * dimensions/fps and total duration are derived from those props in
 * `calculateMetadata`, so the video length follows the (audio-driven) timeline
 * rather than a hard-coded value.
 */

const DEFAULT_PROPS: AutoDemoVideoProps = {
  config: DEFAULT_VIDEO_CONFIG,
  titleCard: {
    title: "AutoDemo — Preview",
    website: "example.com",
    subtitle: "Generated by AutoDemo",
    durationInSeconds: 3,
  },
  scenes: [],
  endCard: { text: "Thanks for watching", durationInSeconds: 2.5 },
  showCursor: false,
  transitionSeconds: 0.5,
};

export function RemotionRoot() {
  return (
    <Composition
      id={AUTODEMO_COMPOSITION_ID}
      component={AutoDemoVideo}
      // Placeholder; overridden by calculateMetadata from real props.
      durationInFrames={Math.max(
        1,
        totalDurationInFrames(DEFAULT_PROPS)
      )}
      fps={DEFAULT_VIDEO_CONFIG.fps}
      width={DEFAULT_VIDEO_CONFIG.width}
      height={DEFAULT_VIDEO_CONFIG.height}
      defaultProps={DEFAULT_PROPS}
      calculateMetadata={({ props }) => {
        return {
          durationInFrames: totalDurationInFrames(props),
          fps: props.config.fps,
          width: props.config.width,
          height: props.config.height,
        };
      }}
    />
  );
}
